#pragma once

typedef enum {
  RESOURCE_NULL = 0,
  RESOURCE_SHADER = 1,
  RESOURCE_MESH = 2,
  RESOURCE_TEXTURE = 3,
  RESOURCE_VULKAN_MESH = 4,
  RESOURCE_VULKAN_MESH_INSTANCE = 5,
  RESOURCE_VULKAN_PIPELINE = 6
} RESOURCE_TYPE;